name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: checking dir
      run: ls
    - name: moving to bin
      script: 
      - cd bin
    - name: checking dir
      run: ls
    - name: running sgbd
      run: ./sgbd.bin
    - name: exiting sgbd
      run: 0
